### ISSUE TITLE
Fel i Safari

### ISSUE THREAD

**Issue by erikdahlstrand** [swanmo/swanmo.github.io#13]
Chrome verkar dock vara mer förlåtande men i Safari så laddas inte programmet
<img width="1169" alt="errors" src="https://cloud.githubusercontent.com/assets/22168/9288145/29ae539a-4338-11e5-9237-5f211ba36368.png">

.

**Comment by swanmo** [comment]
Tog bort alla ES6/ES2015-keywords.
